research_task:
  description: >
    Führe eine tiefgehende Online-Recherche durch, um die neusten Nachrichten, Presseartikel und Blog-Posts zur deutschen Startup-Szene zu finden. Suche nach Schlüsselwörter wie "deutsche Startups", "Finanzierungsrunden Deutschland", "Tech-Innovationen", "German venture capital". 
    Filter nach den wichtigsten und aktuellsten Meldungen der letzten 24 Stunden.
  expected_output: >
    Eine Liste von zehn relevantesten Nachrichten-Headlines, jeweils mit 10 Sätzen Zusammenfassung des Inhalts und dem zugehörgen URL-Link. Die Ausgabe sollte klar und strukturiert sein, bereit für die Übergabe an den reporter.
  agent: researcher
  output_file: output/research.md

reporting_task:
  description: >
    Nimm die recherchierte Liste von Nachrichten-Headlines und Links und erstelle daraus eine kurze, professionelle E-Mail-Zusammenfassung. Jede Nachricht sollte in 5 Sätzen zusammengefasst werden. Beginn die E-Mail mit einer motivierenden Einleitung und beende sie mit einem passenden Gruß. Das Ziel ist es, den Empfänger schnell und effizient über die wichtigsten Geschehnisse des Tages zu informieren.
  expected_output: >
    Ein vollständiger, zur E-Mail-Versendung bereiter Text im Markdown-Format, der die wichtigsten Nachrichten aus der deutschen Startup-Szene des Tages zusammenfasst. Der Text muss klar formatiert sein und einen professionellen und motivierenden Ton haben.
  context:
    - research_task
  agent: reporter
  output_file: output/report.md
